// Copyright © 2025 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

interface ValidInterfacePropertyDeclarations {
    property <bool> implicit-private;
//  ^warning{'private' properties are inaccessible in an interface}

    private property <int> private;
//  ^warning{'private' properties are inaccessible in an interface}

    in property <int> in-property;
    out property <string> out-property;
    in-out property <angle> in-out-property;
    in_out property <angle> in-out-underscore-property;
}

interface InvalidInterfacePropertyDeclarations {
    in-out property <length> valid-for-two-way-binding;
    in-out property two-way-binding <=> valid-for-two-way-binding;
//                  ^error{Missing type. The syntax to declare a property is `property <type> name;`. Two way bindings are not supported in an interface}
//                                  ^^error{Syntax error: expected ';'}
//                                  ^^^error{Parse error}

    out property <bool> default-value: false;
//                                   ^error{Property declarations in an interface cannot have default values}
//                                   ^^error{Syntax error: expected ';'}

    out property <int> index;
    out property <int> next: index + 1;
//                         ^error{Property declarations in an interface cannot have default values}
//                         ^^error{Syntax error: expected ';'}
}
