[package]
name = "sixtyfps_compilerlib"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"

[lib]
path = "lib.rs"

[features]
# Generators
cpp = []
rust = ["quote", "proc-macro2"]

# Support for proc_macro spans in the token (only useful for use within a proc macro)
proc_macro_span = ["quote", "proc-macro2"]

# Feature to print the diagnostics to the console
display-diagnostics = ["codemap", "codemap-diagnostic"]


[dependencies]
m_lexer = "0.0.4" # simple lexer for now
num_enum = "0.4.3"
rowan = "0.10.0"
derive_more = "0.99.5"
codemap-diagnostic = { version = "0.1.1", optional = true }
codemap = { version = "0.1", optional = true }
quote = { version = "1.0", optional = true }
proc-macro2 = { version = "1.0.17", optional = true }
lyon = { version = "0.15.8", features = ["svg"] }
thiserror = "1"
by_address = "1.0.4"


[dev-dependencies]
regex = "1.3.7"
parser_test_macro = { path = "./parser_test_macro" }


