[package]
name = "sixtyfps_compiler"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
m_lexer = "0.0.4" # simple lexer for now
num_enum = "0.4.3"
rowan = "0.10.0"
derive_more = "0.99.5"
structopt = "0.3.14" # FIXME: remove this: bin should be somewhere else

## FIXME remove
[[bin]]
name = "compiler"
path = "main.rs"
test = false
bench = false
