[package]
name = "sixtyfps_compiler"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"

[lib]
path = "lib.rs"

[features]
# cpp: code generator for C++ code
cpp = []

[dependencies]
m_lexer = "0.0.4" # simple lexer for now
num_enum = "0.4.3"
rowan = "0.10.0"
derive_more = "0.99.5"

 # FIXME: remove this: bin should be somewhere else
structopt = "0.3.14"
codemap-diagnostic = "0.1.1"
codemap = "0.1"

[dev-dependencies]
regex = "1.3.7"
parser_test_macro = { path = "./parser_test_macro" }

## FIXME remove
[[bin]]
name = "sixtyfps_compiler"
path = "main.rs"
test = false
bench = false
required-features = ["cpp"]

