[package]
name = "wasmmemory"
version = "0.1.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
publish = false
license = "GPL-3.0-only"
build = "build.rs"

[lib]
crate-type = ["cdylib"]
path = "../main.rs"

[dependencies]
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
sixtyfps = { path = "../../../api/sixtyfps-rs" }

[build-dependencies]
sixtyfps-build = { path = "../../../api/sixtyfps-rs/sixtyfps-build" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features=["console"] }
console_error_panic_hook = "0.1.5"