[package]
name = "memory"
version = "0.1.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
publish = false
license = "GPL-3.0-only"
build = "build.rs"

[[bin]]
path = "main.rs"
name = "memory"

[dependencies]
rand = "0.7.3"
sixtyfps = { path = "../../api/sixtyfps-rs" }

[build-dependencies]
sixtyfps-build = { path = "../../api/sixtyfps-rs/sixtyfps-build" }
