# cSpell: ignore cerr clippy cout cuda oxipng println proto
---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-added-large-files
          - id: fix-byte-order-marker
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-json ### tsconfig.json has non-standard comments
          - id: check-toml
          - id: check-yaml
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-symlinks
          - id: destroyed-symlinks
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: ["--fix=lf"]
    - repo: https://github.com/hunger/pre-commit-hooks.git
      rev: v1.0
      hooks:
          - id: no-debug
    - repo: https://github.com/psf/black
      rev: 23.10.1
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v17.0.4
      hooks:
          - id: clang-format
            types_or: [c++, c, c#, cuda, java, objective-c, proto]
    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: v0.6.13
      hooks:
          - id: cmake-format
          - id: cmake-lint
    - repo: https://github.com/streetsidesoftware/cspell-cli
      rev: v7.3.2
      hooks:
          - id: cspell
    - repo: https://github.com/shssoichiro/oxipng
      rev: v9.0.0
      hooks:
          - id: oxipng
    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
          - id: fmt
          # -   id: cargo-check ### slow...
          # -   id: clippy ### slow...
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.0.3"
      hooks:
          - id: prettier
