[workspace]
members = [
    'sixtyfps_runtime/corelib',
    'sixtyfps_runtime/corelib_macros',
    'sixtyfps_runtime/interpreter',
    'sixtyfps_runtime/rendering_backends/gl',
    'sixtyfps_runtime/rendering_backends/qt',
    'sixtyfps_runtime/rendering_backends/default',
    'sixtyfps_compiler',
    'sixtyfps_compiler/parser_test_macro',
    'api/sixtyfps-rs',
    'api/sixtyfps-rs/sixtyfps-rs-macro',
    'api/sixtyfps-rs/sixtyfps-build',
    'api/sixtyfps-node/native',
    'api/sixtyfps-wasm-interpreter',
    'tools/compiler',
    'tools/viewer',
    'tools/syntax_updater',
    'examples/gallery',
    'examples/gallery/wasm',
    'examples/printerdemo/rust',
    'examples/printerdemo/wasm',
    'examples/todo/rust',
    'examples/todo/wasm',
    'helper_crates/const-field-offset',
    'helper_crates/vtable',
    'helper_crates/vtable/macro',
    'xtask',
    'tests/driver',
    'tests/driver_lib',
    'tests/rustdriver'
]

default-members = [
    'sixtyfps_runtime/corelib',
    'sixtyfps_runtime/interpreter',
    'sixtyfps_runtime/rendering_backends/gl',
    'sixtyfps_runtime/rendering_backends/qt',
    'sixtyfps_runtime/rendering_backends/default',
    'sixtyfps_compiler',
    'api/sixtyfps-rs',
    'api/sixtyfps-rs/sixtyfps-build',
    'api/sixtyfps-node/native',
    'tools/compiler',
    'tools/viewer',
    'tools/syntax_updater',
    'examples/gallery',
    'examples/printerdemo/rust',
    'examples/todo/rust',
    'tests/driver',
    'tests/rustdriver'
]

# Needed to pull in fix for https://github.com/rust-windowing/winit/pull/1736
[patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit", rev = "5a78fe33e84023ca4c89cc30ebeebac0fe89e8f0" }