[package]
name = "zed_slint"
version = "0.0.3"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[dependencies]
zed_extension_api = "0.0.6"

[lib]
path = "src/slint.rs"
crate-type = ["cdylib"]
