[workspace]
members = [
    'sixtyfps_runtime/corelib',
    'sixtyfps_runtime/corelib_macros',
    'sixtyfps_runtime/interpreter',
    'sixtyfps_runtime/rendering_backends/gl',
    'sixtyfps_runtime/rendering_backends/qt',
    'sixtyfps_runtime/rendering_backends/default',
    'sixtyfps_compiler',
    'sixtyfps_compiler/parser_test_macro',
    'api/sixtyfps-rs',
    'api/sixtyfps-rs/sixtyfps-rs-macro',
    'api/sixtyfps-rs/sixtyfps-build',
    'api/sixtyfps-node/native',
    'api/sixtyfps-wasm-interpreter',
    'tools/compiler',
    'tools/viewer',
    'tools/syntax_updater',
    'examples/rusttest',
    'examples/rusttest2',
    'examples/gallery',
    'examples/gallery/wasm',
    'examples/printerdemo/rust',
    'examples/printerdemo/wasm',
    'examples/todo/rust',
    'helper_crates/const-field-offset',
    'helper_crates/vtable',
    'helper_crates/vtable/macro',
    'xtask',
    'tests/driver',
    'tests/driver_lib',
    'tests/rustdriver'
]

exclude = [
    # Exclude the wasm crates from a normal build, they must be build separetaly with the wasm tools
    'examples/gallery/wasm',
    'examples/printerdemo/wasm',
    'api/sixtyfps-wasm-interpreter',
]
