[package]
name = "zed_slint"
version = "0.0.2"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
zed_extension_api = "0.0.5"

[lib]
path = "src/slint.rs"
crate-type = ["cdylib"]
