[workspace]
members = [
    'sixtyfps_runtime/corelib',
    'sixtyfps_runtime/corelib_macros',
    'sixtyfps_runtime/interpreter',
    'sixtyfps_runtime/rendering_backends/gl',
    'sixtyfps_runtime/qt_style',
    'sixtyfps_compiler',
    'sixtyfps_compiler/parser_test_macro',
    'api/sixtyfps-rs',
    'api/sixtyfps-rs/sixtyfps-rs-macro',
    'api/sixtyfps-rs/sixtyfps-build',
    'api/sixtyfps-node/native',
    'tools/compiler',
    'tools/viewer',
    'tools/syntax_updater',
    'examples/graphicstest',
    'examples/rusttest',
    'examples/rusttest2',
    'examples/rustwasmtest',
    'examples/gallery',
    'examples/gallery/wasm',
    'helper_crates/const-field-offset',
    'helper_crates/vtable',
    'helper_crates/vtable/macro',
    'xtask',
    'tests/driver',
    'tests/driver_lib',
    'tests/rustdriver'
]
