id = "slint"
name = "Slint"
description = "Slint support for Zed"
version = "0.0.3"
schema_version = 1
authors = ["Luke. D Jones <luke@ljones.dev>"]
repository = "https://gitlab.com/flukejones/zed-slint"

[language_servers.slint]
name = "Slint LSP"
language = "Slint"

[grammars.slint]
repository = "https://github.com/slint-ui/tree-sitter-slint.git"
commit = "acc77c93ef4b73ba8c3a581b8c99d95b55f7178b"
