[book]
authors = ["SixtyFPS <info@sixtyfps.io>"]
language = "en"
multilingual = false
src = "src"
title = "Slint Memory Game Tutorial (Rust)"

[output.html]
theme = "../theme"

[output.linkcheck]  # enable the "mdbook-linkcheck" renderer
optional = true
