[package]
name = "sixtyfps_corelib"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"

[lib]
path = "lib.rs"

[features]
# Allow the vewer to query at runtime information about item types
rtti = []

[dependencies]
image = { version = "0.23.4", default-features = false, features = [ "png" ] }
cgmath = "0.17.0"
const-field-offset = { path = "../../helper_crates/const-field-offset" }
vtable = { path = "../../helper_crates/vtable" }
corelib_macro = { path = "../corelib_macro" }
winit = "0.22.1"
lyon = { version = "0.15.8" }
euclid = "0.20.11"
servo_arc = "0.1.1" #we need the Arc::from_header_and_iter
once_cell = "1.4"
instant = { version = "0.1", features = [ "now" ] }
derive_more = "0.99.5"
scoped-tls-hkt = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1", features = [ "wasm-bindgen", "now" ] }

[build-dependencies]
cbindgen = "0.14.2"
