[package]
name = "corelib"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"

[lib]
path = "lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
kurbo = "0.5.11"
image = { version = "0.23.4", default-features = false }
cgmath = "0.17.0"
const-field-offset = { path = "../../helper_crates/const-field-offset" }

[build-dependencies]
cbindgen = "0.14.2"
