[package]
name = "corelib"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kurbo = "0.5.11"
image = "0.23.4"
cgmath = "0.17.0"

[build-dependencies]
cbindgen = "0.14.2"
