[package]
name = "sixtyfps-corelib"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0-only"

[lib]
path = "lib.rs"

[features]
# Allow the vewer to query at runtime information about item types
rtti = []

[dependencies]
image = { version = "0.23.4", default-features = false, features = [ "png" ] }
cgmath = "0.17.0"
const-field-offset = { path = "../../helper_crates/const-field-offset" }
vtable = { path = "../../helper_crates/vtable" }
sixtyfps-corelib-macros = { path = "../corelib_macros" }
winit = "0.22.1"
lyon = { version = "0.15.8" }
euclid = "0.20.11"
triomphe = "0.1.1"
once_cell = "1.4"
instant = { version = "0.1", features = [ "now" ] }
derive_more = "0.99.5"
scoped-tls-hkt = "0.1"
static_assertions = "1.1"
strum = "0.19.2"
strum_macros = "0.19.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1", features = [ "wasm-bindgen", "now" ] }
web_sys = { version = "0.3", package = "web-sys", features=["console", "CanvasRenderingContext2d", "TextMetrics"] }
wasm-bindgen = { version = "0.2" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
font-kit = "0.8"
pathfinder_geometry = "0.5.1"

[build-dependencies]
cbindgen = "0.14.2"

[dev-dependencies]
pin-weak = "1"
