[package]
name = "xtask"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"

[dependencies]
structopt = "0.3.14"
cargo_metadata = "0.10.0"
test_driver_lib = { path = "../tests/driver_lib" }
anyhow = "1.0"
lazy_static = "1.4.0"
regex = "1.3.9"
