[package]
name = "const-field-offset-macro"
version = "0.1.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Procedural macro to generate constant field offset from repr(c) struct"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[lib]
path = "macro.rs"
proc-macro = true

[features]
field-offset-trait = []

[dependencies]
syn = { version = "1.0", features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
memoffset = "0.6"
const-field-offset = { path="../" }
