[package]
name = "viewer"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"


[dependencies]
sixtyfps-corelib = { path="../../sixtyfps_runtime/corelib" }
vtable = { path="../../helper_crates/vtable" }
sixtyfps_interpreter = { path = "../../sixtyfps_runtime/interpreter", features=['qt_style'] }
structopt = "0.3.14"
codemap-diagnostic = "0.1.1"
codemap = "0.1"


[[bin]]
name = "viewer"
path = "main.rs"
