# Copyright © SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "slint-cpp"
version = "0.2.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
build = "build.rs"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
description = "Slint C++ integration"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
publish = false
# prefix used to convey path to generated includes to the C++ test driver
links = "slint_cpp"

[lib]
path = "lib.rs"
crate-type = ["lib", "cdylib"]

# Note, these features need to be kept in sync (along with their defaults) in
# the C++ crate's CMakeLists.txt
[features]
backend-gl = ["slint-backend-selector-internal/slint-backend-gl-internal"]
backend-qt = ["slint-backend-selector-internal/slint-backend-qt-internal"]
interpreter = ["slint-interpreter"]
testing = ["slint-backend-testing-internal"] # Enable some function used by the integration tests
wayland = ["slint-backend-selector-internal/wayland"]
x11 = ["slint-backend-selector-internal/x11"]

default = ["backend-gl", "x11", "backend-qt"]

[dependencies]
slint-core-internal = { version = "=0.2.0", path="../../internal/core", features = ["ffi"] }
slint-interpreter = { version = "=0.2.0", path="../../internal/interpreter", default-features = false, features = ["ffi", "compat-0-2-0"], optional = true }
slint-backend-selector-internal = { version = "=0.2.0", path="../../internal/backends/selector" }
slint-backend-testing-internal = { version = "=0.2.0", path="../../internal/backends/testing", optional = true }

[build-dependencies]
anyhow = "1.0"
cbindgen = "0.20"
proc-macro2 = "1.0.11"
