[package]
name = "parser_test_macro"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
publish = false
license = "GPL-3.0-only"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
