[package]
name = "gl"
version = "0.1.0"
authors = ["Simon Hausmann <hausmann@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
