[package]
name = "gl"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sixtyfps_corelib = { package = "corelib", path = "../../corelib" }
glow = { version = "0.4.0", default-features = false }
lyon = { version = "0.15.8" }
kurbo = "0.5.11"
image = { version = "0.23.4", default-features = false }
cgmath = "0.17.0"
