[package]
name = "graphicstest"
version = "0.1.0"
authors = ["Simon Hausmann <simon.hausmann@sixtyfps.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sixtyfps_corelib = { package = "corelib", path = "../../sixtyfps_runtime/corelib" }
sixtyfps_gl_backend = { package = "gl", path = "../../sixtyfps_runtime/rendering_backends/gl" }
kurbo = "0.5.11"
image = { version = "0.23.4", default-features = false, features = [ "png" ] }
cgmath = "0.17.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web_sys = { version = "0.3", package = "web-sys", features=["console"] }
wasm-bindgen = { version = "0.2" }
glow = { version = "0.4.0", default-features = false }
winit = { version = "0.22.1", features = ["web-sys"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = { version = "0.24" }
winit = "0.22.1"
glow = { version = "0.4.0", default-features = false, features = ["web-sys"] }
