[package]
name = "graphicstest"
version = "0.1.0"
authors = ["Simon Hausmann <simon.hausmann@sixtyfps.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sixtyfps_corelib = { package = "corelib", path = "../../sixtyfps_runtime/corelib" }
sixtyfps_rendering_backend_gl = { path = "../../sixtyfps_runtime/rendering_backends/gl" }
image = { version = "0.23.4", default-features = false, features = [ "png" ] }
cgmath = "0.17.0"
winit = "0.22.1"
lyon = "0.15.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }

