[package]
name = "sixtyfps"
version = "0.0.3"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "SixtyFPS Rust API"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[lib]
path = "lib.rs"

[features]
x11 = ["sixtyfps-rendering-backend-default/x11"]
wayland = ["sixtyfps-rendering-backend-default/wayland"]

[dependencies]
once_cell = "1.5"
sixtyfps-macros = { version = "=0.0.3", path = "sixtyfps-macros" }
const-field-offset = { version = "0.1", path = "../../helper_crates/const-field-offset" }
vtable = { version = "0.1.1", path = "../../helper_crates/vtable" }
sixtyfps-corelib = { version = "=0.0.3", path="../../sixtyfps_runtime/corelib" }
sixtyfps-rendering-backend-default = { version = "=0.0.3", path="../../sixtyfps_runtime/rendering_backends/default" }
derive_more = "0.99.5"

[build-dependencies]
rustc_version = "0.3"

# Currently disabled because it does not look good and it depends on external URL which are not stable yet
# [package.metadata.docs.rs]
# rustdoc-args = [ "--html-in-header", "sixtyfps-docs-integration.html" ]
