[package]
name = "sixtyfps"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"

[lib]
path = "lib.rs"

[dependencies]
once_cell = "1.4"
sixtyfps-rs-macro= { path = "sixtyfps-rs-macro" }
const-field-offset = { path = "../../helper_crates/const-field-offset" }
vtable = { path = "../../helper_crates/vtable" }
pin-weak = "1"
sixtyfps-corelib = { path="../../sixtyfps_runtime/corelib" }
# FIXME: should be under a feature or somehow done differently
sixtyfps_rendering_backend_gl = { path="../../sixtyfps_runtime/rendering_backends/gl" }
