// Copyright © SixtyFPS GmbH <info@slint.dev>, Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export interface ScrollView {
    in property <bool> enabled;
    in property <bool> mouse-drag-pan-enabled;
    // FIXME: remove. This property is currently set by the ListView and is used by the native style to draw the scrollbar differently when it has focus
    in-out property <bool> has-focus;
    in-out property <length> viewport-width;
    in-out property <length> viewport-height;
    in-out property <length> viewport-x;
    in-out property <length> viewport-y;
    out property <length> visible-width;
    out property <length> visible-height;
    in property <ScrollBarPolicy> vertical-scrollbar-policy;
    in property <ScrollBarPolicy> horizontal-scrollbar-policy;

    callback scrolled();
}
