// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export interface TextEdit {
    in property <length> font-size;
    in property <string> font-family;
    in property <bool> font-italic;
    in-out property <string> text;
    out property <bool> has-focus;
    in property <bool> enabled;
    in property <bool> read-only;
    in property <TextWrap> wrap;
    in property <TextHorizontalAlignment> horizontal-alignment;
    in property <string> placeholder-text;
    out property <length> visible-width;
    out property <length> visible-height;
    in-out property <length> viewport-x;
    in-out property <length> viewport-y;
    in-out property <length> viewport-width;
    in-out property <length> viewport-height;

    callback edited(text: string);
    callback key-pressed(event: KeyEvent) -> EventResult;
    callback key-released(event: KeyEvent) -> EventResult;

    public function set-selection-offsets(start: int, end: int);
    public function select-all();
    public function clear-selection();
    public function copy();
    public function cut();
    public function paste();
}
