[package]
name = "printerdemo"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"
publish = false

[[bin]]
path = "main.rs"
name = "printerdemo"

[dependencies]
sixtyfps = { path = "../../../api/sixtyfps-rs" }

[build-dependencies]
sixtyfps-build = { path = "../../../api/sixtyfps-rs/sixtyfps-build" }
