[package]
name = "sixtyfps_interpreter"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"

[lib]
path = "lib.rs"


[dependencies]
sixtyfps-corelib = { path = "../corelib", features = ["rtti"] }
sixtyfps_rendering_backend_gl = { path = "../../sixtyfps_runtime/rendering_backends/gl" }
qt_style = { path = "../qt_style", package = 'sixtyfps_qt_style', features = ["rtti"], optional = true }
vtable = { path="../../helper_crates/vtable" }
sixtyfps_compilerlib = { path = "../../sixtyfps_compiler", features = ["display-diagnostics"] }
lyon = { version = "0.15.8" }
derive_more = "0.99.5"
generativity = "1"

