[package]
name = "rusttest"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
publish = false

[dependencies]
sixtyfps = { path = "../../api/sixtyfps-rs" }
