# Copyright © SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "sixtyfps-lsp"
version = "0.2.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2021"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
description = "SixtyFPS LSP server"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
categories = ["gui", "development-tools"]
keywords = ["lsp"]

[package.metadata.bundle]
name = "SixtyFPS Live Preview"
icon = ["../../vscode_extension/extension-logo.png"]

[[bin]]
name = "sixtyfps-lsp"
path = "main.rs"

[features]
sixtyfps-backend-gl = ["slint-interpreter/backend-gl"]
sixtyfps-backend-qt = ["slint-interpreter/backend-qt"]
wayland = ["slint-interpreter/wayland"]
x11 = ["slint-interpreter/x11"]

default = ["sixtyfps-backend-qt", "sixtyfps-backend-gl", "x11"]

[dependencies]
slint-compiler-internal = { version = "=0.2.0", path = "../../internal/compiler"}
slint-core-internal = { version = "=0.2.0", path = "../../internal/core"}
slint-interpreter = { version = "=0.2.0", path = "../../internal/interpreter", default-features = false, features = ["compat-0-2-0"] }
slint-backend-selector-internal = { version = "=0.2.0", path="../../internal/backends/selector" }

clap = { version = "3.0.5", features=["derive", "wrap_help"] }
crossbeam-channel = "0.5"  # must match the version used by lsp-server
dunce = "1.0.1"
euclid = "0.22"
lsp-server = "0.5"
lsp-types = "0.91.0"
once_cell = "1"
serde = "1.0.118"
serde_json = "1.0.60"
spin_on = "0.1"
