[package]
name = "sixtyfps_qt_style"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"

[lib]
path = "lib.rs"

[features]
# Allow the vewer to query at runtime information about item types
rtti = ['sixtyfps-corelib/rtti']


[build-dependencies]
cbindgen = "0.14.2"
cpp_build = "0.5.5"

[dependencies]
const-field-offset = { path = "../../helper_crates/const-field-offset" }
vtable = { path = "../../helper_crates/vtable" }
sixtyfps-corelib-macros = { path = "../corelib_macros" }
sixtyfps-corelib = { path = "../corelib" }
cpp = "0.5.5"
euclid = "0.20.11"

