[package]
name = "sixtyfps-qt-style"
version = "0.0.1"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Qt style for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[lib]
path = "lib.rs"

[features]
# Allow the vewer to query at runtime information about item types
rtti = ['sixtyfps-corelib/rtti']


[build-dependencies]
cbindgen = "0.14.2"
cpp_build = "0.5.5"

[dependencies]
const-field-offset = { version = "0.1", path = "../../helper_crates/const-field-offset" }
vtable = { version = "0.1", path = "../../helper_crates/vtable" }
sixtyfps-corelib-macros = { version = "=0.0.1", path = "../corelib_macros" }
sixtyfps-corelib = { version = "=0.0.1", path = "../corelib" }
cpp = "0.5.5"
euclid = "0.20.11"

