[package]
name = "wasm_sliding_puzzle"
version = "0.1.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
publish= false

[lib]
crate-type = ["cdylib"]
path = "../main.rs"

[dependencies]
sixtyfps = { path = "../../../api/sixtyfps-rs" }
rand = "0.7.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features=["console"] }
console_error_panic_hook = "0.1.5"

[build-dependencies]
sixtyfps-build = { path = "../../../api/sixtyfps-rs/sixtyfps-build" }
