# Copyright © SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "_7gui"
version = "0.2.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
publish = false
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"

[[bin]]
path = "booker.rs"
name = "booker"

[dependencies]
slint = { path = "../../api/rs/slint" }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"]}
