[package]
name = "vtable"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"

[lib]

[dependencies]
vtable-macro = { path="./macro" }
const-field-offset = { path="../const-field-offset" }
