[package]
name = "syntax_updater"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"


[dependencies]
sixtyfps_compiler = { path = "../../sixtyfps_compiler", features = ["display-diagnostics"] }
structopt = "0.3.14"
codemap-diagnostic = "0.1.1"
codemap = "0.1"
rowan = "0.10.0"

[[bin]]
name = "syntax_updater"
path = "main.rs"
