# Copyright © SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "slint-backend-qt-internal"
version = "0.2.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
description = "Qt rendering backend for Slint"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
links = "slint_backend_qt_internal" # just so we can pass metadata to the dependee's build script

[features]
rtti = ["slint-core-internal/rtti"]
default = ["rtti"]

[lib]
path = "lib.rs"

[dependencies]
slint-common-internal = { version = "=0.2.0", path = "../../../internal/common" }
slint-core-macros-internal = { version = "=0.2.0", path = "../../../internal/core-macros" }
slint-core-internal = { version = "=0.2.0", path = "../../../internal/core" }

const-field-offset = { version = "0.1", path = "../../../helper_crates/const-field-offset" }
vtable = { version = "0.1", path = "../../../helper_crates/vtable" }

cpp = "0.5.5"
euclid = "0.22.1"
lyon_path = "0.17"
once_cell = "1"
pin-weak = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
qttypes = { version = "0.2.5", default-features = false }

[build-dependencies]
cpp_build = "0.5.5"
