[package]
name = "sixtyfps_compiler"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"

[[bin]]
name = "sixtyfps_compiler"
path = "main.rs"

[dependencies]
sixtyfps_compilerlib = {path = "../../sixtyfps_compiler", features = ["display-diagnostics", "cpp", "rust"]}
structopt = "0.3.14"
