[package]
name = "sixtyfps-corelib-macros"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
syn = "1.0"
