// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { ExportedInterface as AliasedInterface } from "export_interfaces.slint";

// Implements ExportedInterface under a local alias
export component ExportedBaseViaAlias implements AliasedInterface {
    value: 2.71;
}
