[package]
name = "sixtyfps-node"
version = "0.0.2"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"
# This is not meant to be used as a library from crate.io
publish = false
license = "GPL-3.0-only"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[lib]
path = "lib.rs"
crate-type = ["cdylib"]
name = "sixtyfps_node_native"

[dependencies]
once_cell = "1.4"
sixtyfps-compilerlib = { version = "=0.0.2", path="../../../sixtyfps_compiler", features = ["display-diagnostics"] }
sixtyfps-interpreter = { version = "=0.0.2", path="../../../sixtyfps_runtime/interpreter" }
sixtyfps-corelib = { version = "=0.0.2", path="../../../sixtyfps_runtime/corelib" }
scoped-tls-hkt = "0.1"
neon = "0.5.0"
css-color-parser2 = "1.0.1"
spin_on = "0.1" #FIXME: remove and delegate to async JS instead
vtable = { version = "0.1.1", path="../../../helper_crates/vtable" }
generativity = "1"

[build-dependencies]
neon-build = "0.5.0"


