[package]
name = "sixtyfps-node"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"
# This is not meant to be used as a library from crate.io
publish = false
license = "GPL-3.0-only"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[lib]
path = "lib.rs"
crate-type = ["cdylib"]
name = "sixtyfps_node_native"

[dependencies]
once_cell = "1.4"
sixtyfps-compilerlib = { path="../../../sixtyfps_compiler", features = ["display-diagnostics"] }
sixtyfps-interpreter = { path="../../../sixtyfps_runtime/interpreter" }
sixtyfps-corelib = { path="../../../sixtyfps_runtime/corelib" }
scoped-tls-hkt = "0.1"
neon = "0.5.0"

[build-dependencies]
neon-build = "0.5.0"


