// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { InternalScrollView } from "internal-scrollview.slint";

import {
    ScrollViewInterface,
} from "../common/std-widget-interfaces.slint";

export component ScrollView uses { ScrollViewInterface from internal } {
    min-height: internal.min-height;
    min-width: internal.min-width;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    preferred-height: 100%;
    preferred-width: 100%;

    internal := InternalScrollView {
        @children
    }
}
