[package]
name = "sixtyfps-rs-macro"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
proc-macro2 = "1.0.17"
sixtyfps_compiler = { path = "../../../sixtyfps_compiler", features = ["proc_macro_span", "proc_macro_diagnostics"] }

