[package]
name = "const-field-offset"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"

[dependencies]
const-field-offset-macro = { path = "./macro" }

[dev-dependencies]
memoffset = "0.5.4"
lazy_static = "1.4.0"
