[package]
name = "const-field-offset"
version = "0.1.0"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Wrapper around field-offset crate and const-field-offset-macro"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[dependencies]
const-field-offset-macro = { path = "./macro" }
field-offset = { git = "https://github.com/diggsey/rust-field-offset" }

[dev-dependencies]
memoffset = "0.5.4"
lazy_static = "1.4.0"
