# Copyright © 2024 OTIV B.V.
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

name: Bazel Build
on:
 workflow_dispatch:
 workflow_call:
jobs:
 ci_bazel:
   runs-on: ubuntu-24.04
   steps:
     - uses: actions/checkout@v4
     - uses: ./.github/actions/install-linux-dependencies
     - uses: actions/cache@v4
       with:
         path: ~/.cache/bazel
         key: ${{ runner.os }}-bazel-${{ hashFiles('examples/bazel_build/.bazelversion', 'examples/bazel_build/.bazelrc', 'examples/bazel_build/MODULE.bazel.lock') }}
         restore-keys: |
           ${{ runner.os }}-bazel-

     - name: update packages
       run: sudo apt-get update

     - name: install other system dependencies
       run: sudo apt-get -y install pkg-config libssl-dev default-jre pkgconf

     - name: Bazel Build
       working-directory: examples/bazel_build
       run: bazelisk build --config=ci //...

     - name: Upload bazel-explain build artifact
       uses: actions/upload-artifact@v4
       with:
          name: bazel-explain-build-run
          path: bazel-explain.log
