# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

# Run various formatters, linters, and type-checkers (Rust, C++, TypeScript, etc.)
name: Format, Lint, and type-check

on:
    workflow_call:
    workflow_dispatch:

jobs:
    format_lint_typecheck:
        runs-on: ubuntu-24.04
        env:
            CARGO_INCREMENTAL: false
        steps:
            - uses: actions/checkout@v4
