# LICENSE BEGIN
# This file is part of the SixtyFPS Project -- https://sixtyfps.io
# Copyright (c) 2021 Olivier Goffart <olivier.goffart@sixtyfps.io>
# Copyright (c) 2021 Simon Hausmann <simon.hausmann@sixtyfps.io>
#
# SPDX-License-Identifier: GPL-3.0-only
# This file is also available under commercial licensing terms.
# Please contact info@sixtyfps.io for more information.
# LICENSE END
# Build various demo binaries, c++ packages and documentation and publish them on the website
name: Nightly snapshot

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Dummy
        run: echo ok
