# Copyright © SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

name: Rust Demos built for Torizon

on:
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        description: "Push the built images"
  workflow_call:
    inputs:
      push:
        type: boolean
        description: "Push the built images"

jobs:
  build_containers:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - target: armhf
            image_arch: linux/arm/v7
            rust_toolchain_arch: armv7-unknown-linux-gnueabihf
          - target: arm64
            image_arch: linux/arm64
            rust_toolchain_arch: aarch64-unknown-linux-gnu

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Dockerfile.torizon-demos
        push: ${{ github.event.inputs.push || inputs.push }}
        tags: ghcr.io/slint-ui/slint/slint-torizon-demos-${{matrix.target}}:latest
        build-args: |
          TOOLCHAIN_ARCH=${{matrix.target}}
          IMAGE_ARCH=${{matrix.image_arch}}
          RUST_TOOLCHAIN_ARCH=${{matrix.rust_toolchain_arch}}
