# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.2 OR LicenseRef-Slint-commercial

name: Upload component to Python Package Index

on:
    workflow_dispatch:

jobs:
    build_binaries:
        env:
            MACOSX_DEPLOYMENT_TARGET: "11.0"
        strategy:
            matrix:
                os: [windows-latest, macos-13, macos-14]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v3
            - name: Install cibuildwheel
              run: python -m pip install cibuildwheel==2.17.0  
            - name: Build a binary wheel
              run: python -m cibuildwheel --output-dir wheelhouse
              working-directory: api/python
              env:
                CIBW_BUILD: cp312-*
            - name: Store the distribution packages
              uses: actions/upload-artifact@v4
              with:
                name: python-package-distributions-${{ matrix.os }}-${{ strategy.job-index }}
                path: api/python/wheelhouse/*.whl             

    build_source_package:
        name: Build source package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build source package
              run: pipx run build --sdist
              working-directory: api/python
            - uses: actions/upload-artifact@v4
              with:
                name: python-package-distributions-source
                path: api/python/dist/*.tar.gz                

    publish-to-pypi:
        name: >-
            Publish Python 🐍 distribution 📦 to PyPI
        needs: [build_binaries, build_source_package]
        runs-on: ubuntu-latest
        environment:
            name: testpypi
            url: https://test.pypi.org/p/slint
        permissions:
            id-token: write  # IMPORTANT: mandatory for trusted publishing                
        steps:
            - uses: actions/download-artifact@v4
              with:              
                pattern: python-package-distributions-*
                path: dist
                merge-multiple: true            
            - name: Publish distribution 📦 to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://test.pypi.org/legacy/
