# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.2 OR LicenseRef-Slint-commercial

name: Upload component to Python Package Index

on:
    workflow_dispatch:

jobs:
    build_binaries:
        env:
            MACOSX_DEPLOYMENT_TARGET: "11.0"
        strategy:
            matrix:
                include:
#                    - os: ubuntu-20.04
                    - os: macos-12
                      arch: x86_64
                    - os: macos-14
                      arch: aarch64
                    - os: windows-2022
                      arch: x86_64    
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.x"            
            - name: Install pypa/build
              run: >-
                  python3 -m
                  pip install
                  build
                  --user                
            - name: Build a binary wheel and a source tarball
              run: python3 -m build
              working-directory: api/python
            - name: Store the distribution packages
              uses: actions/upload-artifact@v3
              with:
                name: python-package-distributions-${{ runner.os }}-${{ matrix.arch }}
                path: api/python/dist/              

    publish-to-pypi:
        name: >-
            Publish Python 🐍 distribution 📦 to PyPI
        needs:
            - build_binaries
        runs-on: ubuntu-latest
        environment:
            name: testpypi
            url: https://test.pypi.org/p/slint
        permissions:
            id-token: write  # IMPORTANT: mandatory for trusted publishing                
        steps:
#            - name: Download Linux binary
#              uses: actions/download-artifact@v3
#              with:
#                name: python-package-distributions-Linux
#                path: dist/
            - name: Download Windows binary
              uses: actions/download-artifact@v3
              with:
                name: python-package-distributions-Windows-x86_64
                path: dist/
            - name: Download macOS binary
              uses: actions/download-artifact@v3
              with:
                name: python-package-distributions-macOS-x86_64
                path: dist/
            - name: Download macOS binary
              uses: actions/download-artifact@v3
              with:
                name: python-package-distributions-macOS-aarch64
                path: dist/       
            - name: Publish distribution 📦 to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://test.pypi.org/legacy/
