# LICENSE BEGIN
# This file is part of the SixtyFPS Project -- https://sixtyfps.io
# Copyright (c) 2020 Olivier Goffart <olivier.goffart@sixtyfps.io>
# Copyright (c) 2020 Simon Hausmann <simon.hausmann@sixtyfps.io>
#
# SPDX-License-Identifier: GPL-3.0-only
# This file is also available under commercial licensing terms.
# Please contact info@sixtyfps.io for more information.
# LICENSE END
name: VS Code Extension Build

on:
  workflow_dispatch:

jobs:
  build_lsp:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary_built: sixtyfps-lsp
            artifact_name: sixtyfps-lsp-x86_64-unknown-linux-gnu
          - os: macos-latest
            binary_built: sixtyfps-lsp
            artifact_name: sixtyfps-lsp-x86_64-apple-darwin
          - os: windows-latest
            binary_built: sixtyfps-lsp.exe
            artifact_name: sixtyfps-lsp-x86_64-pc-windows-gnu.exe
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Build LSP
      run: cargo build --release -p sixtyfps-lsp
    - name: Create artifact directory
      run: |
          mkdir bin
          cp ${{ matrix.binary_built }} ${{ matrix.artifact_name }}
    - name: "Upload LSP Artifact"
      uses: actions/upload-artifact@v2
      with:
          name: lsp-binary-${{ matrix.os }}
          path: |
              bin

  build_extension:
    needs: [build_containers]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: lsp-binary-ubuntu-latest
        path: vscode_extension
    - uses: actions/download-artifact@v2
      with:
        name: lsp-binary-windows-latest
        path: vscode_extension
    - uses: actions/download-artifact@v2
      with:
        name: lsp-binary-macos-latest
        path: vscode_extension
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: "Install cross"
      run: cargo install cross
    - name: "Install vsce"
      working-directory: vscode_extension
      run: npm install vsce
    - name: "npm install"
      working-directory: vscode_extension
      run: npm install
    - name: "Build package"
      working-directory: vscode_extension
      run: npx vsce package
    - name: "Upload extension artifact"
      uses: actions/upload-artifact@v2
      with:
          name: sixtyfps-vscode-0.0.1.vsix
          path: |
              vscode_extension/sixtyfps-vscode-0.0.1.vsix
