# LICENSE BEGIN
# This file is part of the SixtyFPS Project -- https://sixtyfps.io
# Copyright (c) 2020 Olivier Goffart <olivier.goffart@sixtyfps.io>
# Copyright (c) 2020 Simon Hausmann <simon.hausmann@sixtyfps.io>
#
# SPDX-License-Identifier: GPL-3.0-only
# This file is also available under commercial licensing terms.
# Please contact info@sixtyfps.io for more information.
# LICENSE END
name: VS Code Extension Build

on:
  workflow_dispatch:

jobs:
  build_lsp:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: x86_64-unknown-linux-gnu
            binary_built: sixtyfps-lsp
            target_dir:
            artifact_name: sixtyfps-lsp-x86_64-unknown-linux-gnu
          - os: macos-latest
            toolchain: x86_64-apple-darwin
            binary_built: sixtyfps-lsp
            target_dir:
            artifact_name: sixtyfps-lsp-x86_64-apple-darwin
          - os: macos-latest
            toolchain: aarch64-apple-darwin
            binary_built: sixtyfps-lsp
            target_dir: aarch64-apple-darwin
            artifact_name: sixtyfps-lsp-aarch64-apple-darwin
          - os: windows-latest
            toolchain: x86_64-pc-windows-gnu
            binary_built: sixtyfps-lsp.exe
            target_dir:
            artifact_name: sixtyfps-lsp-x86_64-pc-windows-gnu.exe
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable-${{ matrix.toolchain }}
    - name: Build LSP
      uses: actions-rs/cargo@v1
      with:
          command: build
          toolchain: stable-${{ matrix.toolchain }}
          args: --release -p sixtyfps-lsp
    - name: Create artifact directory
      run: |
          mkdir bin
          cp target/${{ matrix.target_dir }}/release/${{ matrix.binary_built }} bin/${{ matrix.artifact_name }}
    - name: "Upload LSP Artifact"
      uses: actions/upload-artifact@v2
      with:
          name: lsp-binary-${{ matrix.toolchain }}
          path: |
              bin

  build_extension:
    needs: [build_lsp]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: lsp-binary-x86_64-unknown-linux-gnu
        path: vscode_extension/bin
    - uses: actions/download-artifact@v2
      with:
        name: lsp-binary-x86_64-pc-windows-gnu
        path: vscode_extension/bin
    - uses: actions/download-artifact@v2
      with:
        name: lsp-binary-x86_64-apple-darwint
        path: vscode_extension/bin
    - uses: actions/download-artifact@v2
      with:
        name: lsp-binary-aarch64-apple-darwint
        path: vscode_extension/bin
    - name: Fix permissions
      run: chmod 755 vscode_extension/bin/*
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: "Install vsce"
      working-directory: vscode_extension
      run: npm install vsce
    - name: "npm install"
      working-directory: vscode_extension
      run: npm install
    - name: "Build package"
      working-directory: vscode_extension
      run: npx vsce package
    - name: "Upload extension artifact"
      uses: actions/upload-artifact@v2
      with:
          name: sixtyfps-vscode-0.0.1.vsix
          path: |
              vscode_extension/sixtyfps-vscode-0.0.1.vsix
