# Copyright © SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "i-slint-parser-test-macro"
version = "0.2.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
publish = false
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
